const NOT_LOADED = 1;
const LOADED = 3;

const NO_VENDOR = -1;

const ATTR_ID = 0;
const ATTR_NAME = 1;
const ATTR_TYPE = 2;
const ATTR_ENUM = 3;
const ATTR_REVERSE_ENUM = 4;
const ATTR_MODIFIERS = 5;

const AUTH_START = 4;
const AUTH_END = 20;
const AUTH_LENGTH = 16;
const MESSAGE_AUTHENTICATOR_LENGTH = 16;

module.exports = Object.freeze({
  NOT_LOADED,
  LOADED,
  NO_VENDOR,
  ATTR_ID,
  ATTR_NAME,
  ATTR_TYPE,
  ATTR_ENUM,
  ATTR_REVERSE_ENUM,
  ATTR_MODIFIERS,
  AUTH_START,
  AUTH_END,
  AUTH_LENGTH,
  MESSAGE_AUTHENTICATOR_LENGTH,
});
